{{- if .Values.secrets.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: infraspend-secrets
  labels:
    app: infraspend
type: Opaque
data:
  auth0-domain: {{ index .Values.secrets.infraspendSecrets "auth0-domain" | b64enc | quote }}
  auth0-client-id: {{ index .Values.secrets.infraspendSecrets "auth0-client-id" | b64enc | quote }}
  auth0-audience: {{ index .Values.secrets.infraspendSecrets "auth0-audience" | b64enc | quote }}
  datadog-api-key: {{ index .Values.secrets.infraspendSecrets "datadog-api-key" | b64enc | quote }}
  datadog-app-key: {{ index .Values.secrets.infraspendSecrets "datadog-app-key" | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: infraspend-postgresql
  labels:
    app: infraspend
type: Opaque
data:
  postgres-url: {{ index .Values.secrets.postgresql "postgres-url" | b64enc | quote }}
{{- end }}
